Fix #159 - expose more session fields
clerkinc/clerk-sdk-go pull request #160
Opened 2023-08-24 17:28 UTC by ivanvanderbyl

Fixes #159

2023-08-25 06:32 UTC, gkats requested changes
Thank you for the contribution @ivanvanderbyl 

Left a minor change suggestion.

2023-08-25 07:56 UTC, ivanvanderbyl commented on clerk/sessions.go
> +	LastActiveOrganizationID string `json:"last_active_organization_id"`
Makes sense. I left it out since I couldn't see anywhere that this was being used for marshalling sessions.

2023-08-25 10:29 UTC, gkats commented on clerk/sessions.go
> +	LastActiveOrganizationID string `json:"last_active_organization_id"`
Your instinct was totally right! Thanks for taking care of this.

2023-08-25 10:30 UTC, gkats approved these changes
@ivanvanderbyl Thank you for the contribution! :tada:

2023-08-28 12:06 UTC, dimkl approved these changes

2023-09-08 11:47 UTC, merged