Oauth-token
clerkinc/clerk-sdk-go pull request #75
Opened 2022-09-19 08:48 UTC by Hades32

## Type of change

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] 🌟 New feature (non-breaking change which adds functionality)
- [ ] 🔨 Breaking change (fix or feature that would cause existing functionality)
- [ ] 📖 Docs change / refactoring / dependency upgrade to change)

## Description

Adds a method for the `oauth_access_tokens` endpoint

### Related Issue (optional)

Relates to #72

2022-09-19 15:46 UTC, gkats requested changes
Hey @Hades32, huge thanks for the PR! :raised_hands: 

Overall looks great, I've left a few comments regarding the response type. 

Would you be willing to add a unit test for the new method before we can merge this? Thanks!

2022-09-19 15:46 UTC, gkats commented on clerk/users.go
> +	Label          string      `json:"label"`
The `label` attribute is optional, let's make it a pointer to a `string` instead.
```suggestion
	Label          *string      `json:"label"`
```

2022-09-19 15:46 UTC, gkats commented on clerk/users.go
> +	PublicMetadata interface{} `json:"public_metadata"`
I think the `json.RawMessage` type communicates intent better than the `interface{}` type.
```suggestion
	PublicMetadata json.RawMessage `json:"public_metadata"`
```

2022-09-19 15:46 UTC, gkats commented on clerk/users.go
> +	Scopes         []string    `json:"scopes"`
Turns out that the `scopes` property is available only OAuth 2.0 tokens. Oauth 1.0 tokens use a `token_secret` property.
```suggestion
        // Only set in OAuth 2.0 tokens
	Scopes []string    `json:"scopes,omitempty"`
	// Only set in OAuth 1.0 tokens
	TokenSecret string      `json:"token_secret,omitempty"`
```

2022-09-19 15:46 UTC, gkats commented on clerk/users.go
> +}
@Hades32 Could you please add a unit test for this method in `clerk/users_test.go`? Thanks!

2022-09-19 15:46 UTC, gkats commented on clerk/clerk.go
> +		err = json.NewDecoder(resp.Body).Decode(&v)
:100:

2023-09-08 11:51 UTC, SokratisVidros commented
Closing this, due to the addition of [ListOAuthAccessTokens method](https://github.com/clerkinc/clerk-sdk-go/blob/main/clerk/users.go#L249)

2023-09-08 11:51 UTC, closed without merging